POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Joao Teste",
  "email": "joao@teste.com",
  "password": "Senha123"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "joao@teste.com",
  "password": "Senha123"
}